### ISSUE TITLE
Mass inconsistencies in ship data

### ISSUE THREAD

**Issue by alistair3149** [StarCitizenWiki/scunpacked#1]
The mass on Carrack is incorrect, seems that it is missing exactly 4.3mil kg (4,397,858 Kg vs 97,858 Kg).

It seems that both #DPSCalucator and Ship Performance Viewer got the right number, perhaps there's a bug with SCUnpacked or the data itself?

**Comment by octfx** [comment]
So the raw data for the carrack shows the following:
```xml
<Part name="ANVL_Carrack" class="Animated" mass="97858‬.0d" disablePhysics="0" scopeContext="Ship">
```

I guess the only way to fix this is to manually set the mass for the carrack(s)?

**Comment by octfx** [comment]
Mass is manually overridden for the carrack in commit fa6d1424f981ea9ae19a3e7c4413e76c249f37a8
