### ISSUE TITLE
Vehicle insurance claim and expedite time should be flipped

### ISSUE THREAD

**Issue by alistair3149** [StarCitizenWiki/scunpacked#2]
Take Carrack for example:
```json
"insurance": {
    "claim_time": 15,
    "expedite_time": 45,
    "expedite_cost": 22500
},
```

The expedite time should be 15 min and the claim time be 45 min, seems that it is inverted now

**Comment by octfx** [comment]
Fixed in 0c16b8a7b035673dea8774c89c8801005358280b
